hay-kot/homebox

README.md
backend/ent/item.go
backend/ent/item/item.go
backend/ent/item/where.go
backend/ent/item_create.go
backend/ent/item_update.go
backend/ent/migrate/schema.go
backend/ent/mutation.go
backend/ent/runtime.go
backend/ent/schema/item.go
backend/ent/schema/label.go
backend/ent/schema/location.go
backend/internal/repo/repo_items_test.go
backend/internal/services/service_items.go
backend/internal/services/service_items_csv.go
backend/internal/services/service_items_csv_test.go
backend/internal/services/service_items_test.go
backend/internal/types/item_types.go
docs/docs/assets/stylesheets/extras.css
docs/docs/import-csv.md
docs/mkdocs.yml

Add all columns to CSV importer
Add stub value for ImportRef field for future use
Add Docs for CSV importer

fix: csv-importer

---

frontend/components/App/Header.vue
frontend/components/Base/Card.vue
frontend/components/Label/CreateModal.vue
frontend/components/Location/CreateModal.vue
frontend/components/global/DetailsSection/DetailsSection.vue
frontend/components/global/DetailsSection/index.ts
frontend/components/global/DetailsSection/types.ts
frontend/components/global/PasswordScore.vue
frontend/composables/use-confirm.ts
frontend/composables/use-password-score.ts
frontend/lib/api/user.ts
frontend/lib/passwords/index.test.ts
frontend/lib/passwords/index.ts
frontend/lib/strings/index.test.ts
frontend/package.json
frontend/pages/home.vue
frontend/pages/index.vue
frontend/pages/item/[id]/edit.vue
frontend/pages/item/[id]/index.vue
frontend/pages/label/[id].vue
frontend/pages/location/[id].vue
frontend/pnpm-lock.yaml
frontend/stores/auth.ts
frontend/test/vitest.config.ts

_(REQUIRED)_
- bug
- cleanup
- feature
_(REQUIRED)_
_(REQUIRED)_
_(REQUIRED)_
```release-note
```

chore: cleanup

---

Taskfile.yml
backend/app/api/docs/docs.go
backend/app/api/docs/swagger.json
backend/app/api/docs/swagger.yaml
backend/internal/services/service_user.go
frontend/components/App/Header.vue
frontend/components/Item/CreateModal.vue
frontend/components/global/DateTime.vue
frontend/lib/api/__test__/public.test.ts
frontend/lib/api/__test__/test-utils.ts
frontend/lib/api/types/data-contracts.ts
frontend/pages/index.vue
frontend/pages/item/[id]/index.vue

- bugs
- UX improvements
Fixes:
UX:

fix: multiple-bugs

---

Taskfile.yml
backend/app/api/docs/docs.go
backend/app/api/docs/swagger.json
backend/app/api/docs/swagger.yaml
backend/app/api/routes.go
backend/app/api/v1/v1_ctrl_auth.go
backend/app/api/v1/v1_ctrl_user.go
backend/internal/repo/repo_users.go
backend/internal/services/service_user.go
frontend/lib/api/__test__/factories/index.ts
frontend/lib/api/__test__/public.test.ts
frontend/lib/api/__test__/test-utils.ts
frontend/lib/api/__test__/user/labels.test.ts
frontend/lib/api/__test__/user/locations.test.ts
frontend/lib/api/__test__/user/user.test.ts
frontend/lib/api/base/base-api.ts
frontend/lib/api/classes/users.ts
frontend/lib/api/types/data-contracts.ts
frontend/pages/profile.vue

_(REQUIRED)_
- feature
_(REQUIRED)_
implement change password feature for users
_(REQUIRED)_
partial - #17 
added workflow test for e2e tests

feat: change password

---

frontend/components/Form/Select.vue

fix select-first to update on items change

---

frontend/components/Form/Select.vue
frontend/components/Item/CreateModal.vue
frontend/pages/item/[id]/edit.vue

fix: auto-select bug

---

frontend/pages/index.vue
frontend/pages/profile.vue

feat: show app version

---

docs/docs/quick-start.md

fix compose example
- https://github.com/hay-kot/homebox/discussions/63

docs: fix compose example

---

backend/app/api/routes.go
backend/app/api/v1/controller.go
backend/app/api/v1/v1_ctrl_user.go
backend/internal/config/conf.go
docs/docs/quick-start.md
frontend/lib/api/types/data-contracts.ts

feat: allow disable registration

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
Taskfile.yml

chore: init dev container

---

frontend/components/Form/Select.vue
frontend/pages/item/[id]/edit.vue
frontend/pages/profile.vue

fix: selector value binding

---

backend/ent/attachment/attachment.go
backend/ent/migrate/schema.go
backend/ent/schema/attachment.go
frontend/lib/api/types/non-generated.ts
frontend/pages/item/[id]/edit.vue
frontend/pages/item/[id]/index.vue

feat: add receipt support for attachments

---

.github/workflows/partial-backend.yaml
.github/workflows/partial-frontend.yaml
backend/internal/core/services/service_items_csv_test.go
docs/docs/import-csv.md
frontend/components/global/DateTime.vue
frontend/lib/api/base/base-api.ts

fix: time-format-inconsistency

---

frontend/components/Item/CreateModal.vue
frontend/components/Label/CreateModal.vue
frontend/components/Location/CreateModal.vue

feat: redirect-on-create

---

backend/internal/data/ent/group/group.go
backend/internal/data/ent/migrate/schema.go
backend/internal/data/ent/schema/group.go
frontend/lib/data/currency.ts

feat: add currencies (NOK, SEK, DKK)

---

backend/internal/data/ent/group/group.go
backend/internal/data/ent/migrate/schema.go
backend/internal/data/ent/schema/group.go
frontend/lib/data/currency.ts

feat: add INR currency and sort currencies

---

backend/internal/data/repo/repo_items.go

feat: include notes in search

---

backend/app/api/handlers/v1/v1_ctrl_items.go
backend/internal/core/services/service_items_csv.go
backend/internal/core/services/service_items_csv_test.go
backend/internal/core/services/testdata/import.csv
backend/internal/core/services/testdata/import.tsv
docs/docs/import-csv.md
frontend/pages/home.vue

feat: add tsv support for import files

---

backend/app/api/handlers/v1/v1_ctrl_items_attachments.go

fix: assign extension if not set

---

frontend/components/Item/CreateModal.vue

feat: present loc/labels based on route

---

docs/docs/import-csv.md

Fixes typo in header snippet in docs/docs/import-csv.md
See above.

Fix typo in documentation (import-csv.md)

---

frontend/components/global/DetailsSection/DetailsSection.vue
frontend/components/global/DetailsSection/types.ts
frontend/components/global/Markdown.vue
frontend/package.json
frontend/pages/item/[id]/index.vue
frontend/pages/label/[id].vue
frontend/pages/location/[id].vue
frontend/pnpm-lock.yaml

add markdown support for large text fields

feat: markdown support

---

.vscode/settings.json
frontend/assets/css/main.css
frontend/components/Item/Card.vue
frontend/components/Item/CreateModal.vue
frontend/components/global/CopyText.vue
frontend/components/global/DetailsSection/DetailsSection.vue
frontend/components/global/DetailsSection/types.ts
frontend/composables/use-preferences.ts
frontend/lib/api/types/data-contracts.ts
frontend/pages/item/[id]/index.vue
frontend/pages/item/[id]/index/edit.vue
frontend/pages/item/[id]/index/log.vue
frontend/pages/profile.vue

Closes #200
Closes #230 
Closes #241
Partial work for #14

refactor: refactor item page UI

---

frontend/lib/data/currency.ts

Adding Bulgarian lev to list of currencies
- feature
Adding support for new type of currency
none
```
Adding Bulgarian lev to list of user currencies
```

Adding new currency

---

frontend/components/Form/DatePicker.vue
frontend/composables/use-formatters.ts
frontend/lib/api/classes/stats.ts

Potential fix for #236
closes #48 
closes #81

feat: use native date picker + align date formats

---

backend/internal/data/repo/repo_locations.go
frontend/components/Item/CreateModal.vue
frontend/lib/api/base/base-api.ts

- makes name sort case insensitive for tree items
- replace old location selector with new one
- Fixes date time error in https://github.com/hay-kot/homebox/issues/236#issuecomment-1407660440

fix: tree fixes

---

backend/app/api/handlers/v1/v1_ctrl_auth.go
backend/app/api/handlers/v1/v1_ctrl_items.go
backend/app/api/routes.go
backend/app/api/static/docs/docs.go
backend/app/api/static/docs/swagger.json
backend/app/api/static/docs/swagger.yaml
backend/internal/data/repo/asset_id_type.go
backend/internal/data/repo/repo_items.go
backend/internal/data/repo/repo_items_test.go
backend/internal/data/repo/repo_users.go
frontend/components/App/ImportDialog.vue
frontend/composables/use-api.ts
frontend/composables/use-events.ts
frontend/layouts/default.vue
frontend/lib/api/classes/items.ts
frontend/lib/api/types/data-contracts.ts
frontend/lib/requests/requests.ts
frontend/pages/items.vue

To Do's
---
Closes #181 
- Advanced search is no longer reactive, it now requires you to press "Search." When working with fields it caused a lot of page re-rendering that was less than ideal. This is an easy fix without sacrificing too much usability. 
You can now query Asset ID's with `#` prefix
You can not select/filter on multiple custom fields. Keys/Values will appear in the dropdown fields.

feat: enhanced search functions

---

backend/internal/core/services/service_user.go
backend/internal/data/repo/repo_items.go

fix: prevents re-creating locations and labels when someone joins group

---

frontend/components/Form/Password.vue
frontend/pages/index.vue
frontend/pages/profile.vue

feat: toggle view of password field

---

frontend/components/Item/View/Table.vue
frontend/pages/home/index.vue
frontend/pages/home/table.ts
frontend/pages/item/[id]/index.vue
frontend/pages/label/[id].vue

feat: implement selectable view + sortable table

---

frontend/components/App/ImportDialog.vue
frontend/components/DetailAction.vue
frontend/layouts/default.vue
frontend/lib/api/types/data-contracts.ts
frontend/pages/profile.vue
frontend/pages/tools.vue
scripts/process-types/main.go

Work towards #227 and #16 
Mostly just making a place for things on the frontend

init tools page

---

frontend/pages/reports/label-generator.vue
frontend/pages/tools.vue

MVP for printable labels
Currently the defaults work for Avery 5260 labels, however the interface provides tune-able parameters.
Linked discussion on feature page for improvements.
- https://github.com/hay-kot/homebox/discussions/273
Closes #227

feat: mvp for label generation/printing

---

frontend/components/Form/DatePicker.vue
frontend/lib/api/base/base-api.ts
frontend/pages/item/[id]/index/edit.vue

refactor: editor page

---

frontend/components/Form/Autocomplete2.vue

fix: dropdown color issue

---

frontend/pages/index.vue

fix button display on light mode

---

backend/internal/data/repo/repo_locations.go

use item quantity as count mechanism

---

frontend/pages/index.vue
frontend/pages/label/[id].vue
frontend/pages/location/[id].vue

fix: several layout issues

---

backend/internal/data/repo/repo_locations.go

Add support for displaying nested items within items in the tree view

feat: support item nesting in tree view

---

backend/go.sum
backend/internal/data/ent/group/group.go
backend/internal/data/ent/migrate/schema.go
backend/internal/data/ent/schema/group.go
frontend/lib/data/currency.ts

- feature
adds new currency Swiss Francs.
I hope I did everything as expected. the task "pr" failed but the db generate was successful.
```
add currency Swiss Francs
```

Add Currency Swiss Francs

---

backend/go.sum
backend/internal/data/ent/group/group.go
backend/internal/data/ent/migrate/schema.go
backend/internal/data/ent/schema/group.go
frontend/lib/data/currency.ts

Closes #310
Closes #309
Closes #279

feat: more-currency-support

---

backend/app/api/handlers/v1/v1_ctrl_maint_entry.go
backend/app/api/static/docs/docs.go
backend/app/api/static/docs/swagger.json
backend/app/api/static/docs/swagger.yaml
backend/internal/data/ent/maintenanceentry.go
backend/internal/data/ent/maintenanceentry/maintenanceentry.go
backend/internal/data/ent/maintenanceentry/where.go
backend/internal/data/ent/maintenanceentry_create.go
backend/internal/data/ent/maintenanceentry_update.go
backend/internal/data/ent/migrate/schema.go
backend/internal/data/ent/mutation.go
backend/internal/data/ent/runtime.go
backend/internal/data/ent/schema/maintenance_entry.go
backend/internal/data/migrations/migrations/20230227024134_add_scheduled_date.sql
backend/internal/data/migrations/migrations/atlas.sum
backend/internal/data/repo/repo_maintenance_entry.go
backend/internal/data/repo/repo_maintenance_entry_test.go
frontend/components/Form/DatePicker.vue
frontend/composables/utils.ts
frontend/lib/api/__test__/user/items.test.ts
frontend/lib/api/classes/items.ts
frontend/lib/api/types/data-contracts.ts
frontend/pages/item/[id]/index.vue
frontend/pages/item/[id]/index/maintenance.vue
scripts/process-types/main.go

Adds basic support for scheduled maintenance tasks

feat: add scheduled maintenance tasks

---

backend/internal/data/ent/group/group.go
backend/internal/data/ent/migrate/schema.go
backend/internal/data/ent/schema/group.go
frontend/lib/data/currency.ts

- feature
- adding czcech currency czk, more usable for users from Czechia :) 
not fixing any issue
```release-note
Add support for Czech currency CZK 
```

feat: add czech currency czk

---

backend/internal/data/ent/group/group.go
backend/internal/data/ent/migrate/schema.go
backend/internal/data/ent/schema/group.go
frontend/lib/data/currency.ts

- feature
_(REQUIRED)_
- Adds the New Zealand Dollar (NZ$) as a currency option
N/A
```
Adding the New Zealand Dollar as a supported currency
```

Adding NZD currency

---

backend/app/api/handlers/v1/controller.go
backend/app/api/main.go
backend/app/api/static/docs/docs.go
backend/app/api/static/docs/swagger.json
backend/app/api/static/docs/swagger.yaml
docs/docs/api/openapi-2.0.json
frontend/pages/index.vue

feat: change shit to things

---

frontend/composables/use-auth-context.ts
frontend/nuxt.config.ts
frontend/pages/index.vue

fix redirect issues for authorized users

---

backend/app/api/handlers/v1/v1_ctrl_items.go
backend/internal/data/repo/repo_items.go
frontend/components/Base/Card.vue
frontend/components/Item/View/Table.vue
frontend/layouts/default.vue
frontend/lib/api/classes/items.ts
frontend/pages/home/table.ts
frontend/pages/profile.vue

closes #330 
closes #342
closes #329

fix: other minor fixes

---

backend/internal/sys/validate/validate.go

Fix generic webhook support for Shoutrrr notifications
Related to 
- #396

fix: add generic shoutrr prefix to validators

---

frontend/composables/use-auth-context.ts
frontend/package.json
frontend/pnpm-lock.yaml

Bump Nuxt + Fix Cookie Ref
- chore
_(REQUIRED)_
_(REQUIRED)_
_(REQUIRED)_
```release-note
```

bump nuxt + fix CookieRef

---

backend/app/api/handlers/v1/v1_ctrl_items.go
backend/app/api/routes.go
backend/app/api/static/docs/docs.go
backend/app/api/static/docs/swagger.json
backend/app/api/static/docs/swagger.yaml
backend/app/tools/typegen/main.go
backend/go.sum
backend/internal/data/repo/repo_items.go
docs/docs/api/openapi-2.0.json
frontend/lib/api/classes/items.ts
frontend/lib/api/types/data-contracts.ts
frontend/lib/requests/requests.ts
frontend/package.json
frontend/pages/item/[id]/index.vue
frontend/pages/item/[id]/index/edit.vue
frontend/pnpm-lock.yaml

Adds +/- buttons for incrementing quantity quickly.

feat: easily increment quantity

---

backend/go.sum
backend/internal/data/ent/group/group.go
backend/internal/data/ent/migrate/schema.go
backend/internal/data/ent/schema/group.go
frontend/lib/data/currency.ts

feat: more currency support

---

backend/app/api/routes.go
frontend/lib/api/classes/assets.ts

fix: assert/asserts

---

frontend/components/Form/Password.vue

fix: label prop not being passed to password input

---

frontend/pages/item/[id]/index.vue
frontend/pages/item/[id]/index/edit.vue

feat: support cmd+s / ctrl+s and rework button display on edit

---

frontend/composables/use-defer.ts
frontend/pages/item/[id]/index/maintenance.vue

fix: resetting dialog on error

---

frontend/composables/use-server-events.ts
frontend/package.json
frontend/pnpm-lock.yaml

_(REQUIRED)_
- bug
_(REQUIRED)_
Closes #541 
_(REQUIRED)_
```release-note
```

fix websocket over secure connection

---

docs/docs/quick-start.md

_(REQUIRED)_
_(REQUIRED)_
Fixed minor typo
_(REQUIRED)_
Fixed minor typo
_(REQUIRED)_
```release-note
Fix minor typo - change "in" to "if" in environment variable documentation section
```

Fix minor typo

---

frontend/components/Item/CreateModal.vue
frontend/components/Label/CreateModal.vue
frontend/components/Location/CreateModal.vue

ensure loading in toggled

---

backend/app/api/handlers/v1/v1_ctrl_items.go

fix: field values request fails

---

frontend/package.json
frontend/pnpm-lock.yaml

Revert "chore(deps): update dependency nuxt to v3.7.4"

---

frontend/pages/location/[id].vue

_(REQUIRED)_
- bug
Fixes missing child locations from locations page
closes #586

fix: restore location section

---

backend/internal/data/migrations/migrations.go

_(REQUIRED)_
- bug
_(REQUIRED)_
_(REQUIRED)_
Closes #445
_(REQUIRED)_
```release-note
```

fix: use unix filepath sep on windows for embeds

---

backend/internal/sys/validate/validate.go

_(REQUIRED)_
- bug
_(REQUIRED)_
- Adds validation for `ntfy://` prefix
- Also just catches up to current Shoutrrr supported services, including [`generic+` as a prefix](https://containrrr.dev/shoutrrr/0.7/services/generic/#shortcut_url)
_(REQUIRED)_
Fixes #590
Will be part of this PR, looking at GitHub Actions workflows. Simple change too, expecting no issues
_(REQUIRED)_
```release-note
Validation catch-up to Shoutrrr's current service list
```

Add Shoutrrr validation for `bark://`, `ntfy://` and `generic+` prefixes

---

frontend/pages/label/[id].vue
frontend/pages/location/[id].vue

_(REQUIRED)_
- bug
_(REQUIRED)_
Closes #589

fix: use theme aware background color

---

backend/app/api/handlers/v1/v1_ctrl_items.go
backend/app/api/main.go
backend/app/api/routes.go
backend/internal/core/services/reporting/eventbus/eventbus.go
backend/internal/data/repo/main_test.go
backend/internal/sys/config/conf.go
docs/docs/quick-start.md

_(REQUIRED)_
- feature
_(REQUIRED)_
Exposes web timeouts for configuration
_(REQUIRED)_
Closes #596
_(REQUIRED)_
```release-note
```

feat: expose timeout variables

---

backend/internal/data/repo/asset_id_type.go
backend/internal/data/repo/repo_items.go

_(REQUIRED)_
- bug
_(REQUIRED)_
Closes #599

fix: allow zeroing out asset ids

---

CONTRIBUTING.md
docs/docs/import-csv.md
docs/docs/index.md
docs/docs/tips-tricks.md

_(REQUIRED)_
- cleanup
_(REQUIRED)_
Miscellaneous small grammar/spelling improvements.
_(REQUIRED)_
/
Of course open for suggestions/improvements
/
_(REQUIRED)_
```release-note
NONE
```

Fix a bunch of grammar and spelling, rephrased some sentences to be more readable

---

frontend/pages/item/[id]/index/edit.vue

_(REQUIRED)_
- bug
_(REQUIRED)_
Rendering HTML before initial load caused stale HTML to be rendered and not re-rendered. 
Closes #548
_(REQUIRED)_
_(REQUIRED)_
```release-note
```

fix: loading causing stale data to present in form

---

frontend/nuxt.config.ts

_(REQUIRED)_
- bug
_(REQUIRED)_
Service worker is caching HTML responses blocking exports. 
Closes #640 
_(REQUIRED)_
Manual testing

fix: ignore /api paths from service workers

---

frontend/composables/use-api.ts
frontend/composables/use-auth-context.ts
frontend/middleware/auth.ts

feat: add log statements + remove auto redirect

---

backend/.golangci.yml
backend/app/api/handlers/v1/v1_ctrl_group.go
backend/app/api/handlers/v1/v1_ctrl_items.go
backend/internal/sys/config/conf.go

_(REQUIRED)_
- cleanup
_(REQUIRED)_
* Enable `gofmt` golangci-lint linter to ensure conformance of Go source code to `gofmt` conventions
* Run `gofmt -s -w .` over backend source tree to fix all outstanding issues
_(REQUIRED)_
Several parts of the codebase are not currently formatted per gofmt conventions.
N/A
_(REQUIRED)_
```release-note
NONE
```

backend: Enable gofmt in linter configuration, fix all outstanding errors

---

backend/app/api/handlers/v1/controller.go

_(REQUIRED)_
- feature
_(REQUIRED)_
This change:
* Adds an asynchronous timer that sends the client aliveness pings every 10s following a connection to `/api/v1/ws/events`
* Migrates the event message serialization logic to structured encoding leveraging `encoding/json`
_(REQUIRED)_
When Homebox is deployed behind a reverse proxy that enforces upstream I/O timeouts, and there are no events available to broadcast over the realtime event stream, the web client will continuously reconnect to `/api/v1/ws/events` every `(proxy-enforced read header timeout duration)` due to proxy-initiated connection terminations/disconnects.
This PR proposes sending the client aliveness pings every 10s following the initial connection, to be robust against any such behavior.
Note that no client-side changes …

backend: Periodically send client aliveness pings in event stream websocket connection

---

backend/internal/data/repo/repo_items.go
frontend/components/Form/DatePicker.vue
frontend/components/global/DateTime.vue
frontend/composables/use-formatters.ts
frontend/composables/use-theme.ts
frontend/lib/datelib/datelib.test.ts
frontend/lib/datelib/datelib.ts
frontend/package.json
frontend/pnpm-lock.yaml

_(REQUIRED)_
- bug
Current date picker is less than ideal
Closes #464

fix: date picker improvements

---

backend/app/api/app.go
backend/app/api/bgrunner.go
backend/app/api/main.go
backend/go.mod
backend/go.sum
backend/internal/core/services/reporting/eventbus/eventbus.go
backend/internal/data/repo/main_test.go
backend/internal/sys/config/conf.go
backend/internal/web/mid/errors.go
frontend/components/Form/DatePicker.vue

chore: bump http kit
