frontend/components/Form/TextArea.vue
frontend/components/Item/CreateModal.vue
frontend/components/Location/CreateModal.vue
frontend/composables/use-api.ts
frontend/composables/use-events.ts
frontend/layouts/home.vue
frontend/pages/home.vue
frontend/pages/item/[id]/edit.vue
frontend/pages/item/[id]/index.vue
frontend/stores/items.ts
frontend/stores/labels.ts
frontend/stores/locations.ts

implemented a store for each global item and tied it to an event bus and used the listener on the requests object to intercept responses from the API and run the appropriate get call when updates were detected.

fix(frontend): fix mis-matched state errors

---

frontend/pages/index.vue
frontend/pages/item/[id]/index.vue
frontend/pages/items.vue

- bug
homebox\frontend\pages\item\[id]\index.vue
- Resolved spelling error for **Model Number**
- Fixes #64 
homebox\frontend\pages\index.vue
- Updated Discord and Docs links to open in new tabs/windows, following the behaviour of the GitHub and Twitter links
- Fixes #66 
homebox\frontend\pages\items.vue
- Resolved spelling error for second occurrence of **Labels**, changing it to **Locations**
- Fixes #67
Fixes #64 
Fixes #66 
Fixed #67
```
- Resolved spelling error for Model Number on item page
- Updated Discord and Docs links to open in new tabs/windows, following the behaviour of the GitHub and Twitter links on the login page
- Resolved spelling error for second occurrence of Labels in the filter section on the items page, changing it to Locations
```

fix(s): spelling mistakes, and external link handling on login page

---

frontend/pages/item/[id]/edit.vue
frontend/pages/item/[id]/index.vue

Updated wording across item index and edit page for consistency, as they currently differ.
- cleanup
homebox\frontend\pages\item\[id]\edit.vue
- Changed **Purchased Price** to **Purchase Price** to match index.vue
- Changed **Purchased At** to **Purchase date** to match index.vue
homebox\frontend\pages\item\[id]\edit.vue
- Changed **Purchase From** to **Purchased From** to match edit.vue
- Change section header **Purchase** to **Purchase Details** to match edit.vue
- Change section header **Warranty** to **Warranty Details** to match edit.vue
- Change section header **Sold** to **Sold Details** to match edit.vue
```
Spelling changes to section and field titles to resolve spelling differences between item view and edit page.
```

Consistency changes to item pages

---

backend/internal/repo/repo_items.go
backend/internal/repo/repo_labels.go
backend/internal/repo/repo_locations.go

closes #73
This implementation is case sensitive, but I don't think that will be too much of an issue since you would generally always capitalize the name of an item. Either way, as long as you're consistent it should be fine.

feat: order labels and locations by name

---

backend/app/api/handlers/v1/query_params.go
backend/app/api/handlers/v1/v1_ctrl_items.go
backend/app/api/handlers/v1/v1_ctrl_locations.go
backend/app/api/static/docs/docs.go
backend/app/api/static/docs/swagger.json
backend/app/api/static/docs/swagger.yaml
backend/internal/core/services/service_items.go
backend/internal/core/services/service_items_test.go
backend/internal/data/repo/repo_locations.go
backend/internal/data/repo/repo_locations_test.go
frontend/components/Item/CreateModal.vue
frontend/layouts/default.vue
frontend/lib/api/classes/locations.ts
frontend/pages/home.vue
frontend/pages/item/[id]/edit.vue
frontend/pages/items.vue
frontend/pages/location/[id].vue
frontend/stores/locations.ts

closes #132 
This is a temporary fix to solve #132, but it does result in over-fetching data on the frontend. It shouldn't have any significant cost for users, so I'm going to add this issue to the backlog and we'll get it resolved when we can.

fix: conditionally filter parent locations

---

backend/app/api/handlers/v1/v1_ctrl_actions.go
backend/app/api/routes.go
backend/app/api/static/docs/docs.go
backend/app/api/static/docs/swagger.json
backend/app/api/static/docs/swagger.yaml
backend/internal/data/repo/repo_items.go
frontend/assets/css/main.css
frontend/components/Form/DatePicker.vue
frontend/lib/api/classes/actions.ts
frontend/lib/api/types/data-contracts.ts
frontend/pages/profile.vue

New Action to _hopefully_ resolve issue described in 
- #236 
- https://github.com/hay-kot/homebox/issues/236#issuecomment-1408125626
Times were previously being saved with Date _and_ time data, this function resets all the time data and only keeps the date values. This should hopefully resolve the issues of dates being different between the frontend and the backend for some users. 
Also fixes some API documentation and the zero values from showing up in the date field

fix: add custom action for fixing broken date/times

---

backend/internal/data/repo/repo_items.go
frontend/assets/css/main.css
frontend/components/Form/Autocomplete2.vue
frontend/components/Location/Selector.vue
frontend/components/Search/Filter.vue
frontend/composables/use-location-helpers.ts
frontend/lib/api/types/data-contracts.ts
frontend/package.json
frontend/pages/items.vue
frontend/pnpm-lock.yaml

Closes #255 
Reworks search UI to support nested location selection and cleanups up the UI quite a bit. Also fixes a search bug where Location/Label/Field queries were not applied in an expected way. 
Now item results must have 1 of the locations, one of the labels, and one of the fields. Before only one of any of the criteria would need to have been met.

feat/fix: search location selectors

---

frontend/lib/api/types/data-contracts.ts
scripts/process-types/main.go

regular expressions are order specific and when applied in a random order you can get a variety of outputs. Using a list preserves order and ensures that the data-contracts.ts file is deterministic.

fix :code generation and type processing

---

Dockerfile

_(REQUIRED)_
- documentation (ish)
This adds the `org.opencontainers.image.source` label to the Dockerfile (and thus docker image) pointing to this repository for cross-referencing information. 
None documented.
This is purely a label for other tooling to reference, as noted here: https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/readme.md
I have not personally tested this change as it is just adding a label.
```release-note
NONE
```

build(docker): add image source label

---

frontend/components/Base/Card.vue
frontend/components/global/DetailsSection/types.ts
frontend/pages/item/[id]/index.vue

filter details for zero values

---

backend/app/api/handlers/v1/v1_ctrl_items.go
backend/internal/data/types/date.go
docs/docs/import-csv.md
frontend/components/Base/Card.vue
frontend/pages/tools.vue

fix: various minor bugs

---

.devcontainer/devcontainer.json

I noticed that the devcontainer setup threw an error about tiny not supporting go 1.19, so I tried to figure out the problem. It turned out that in the devcontainer.json go 1.19 was requested while in the go.mod file already go 1.20 was used.

update go version in devcontainer to 1.20 to match version in go.mod

---

.github/workflows/partial-publish.yaml
Dockerfile
Dockerfile.rootless
README.md
docs/docs/quick-start.md

- feature
This PR attempts to accomplish the following:
* Minimize the image size
* Minimize the attack surface for the application (distroless images will not include `busybox` or a shell in general)
* Avoid running the application as `root` as it's not required. In fact, since the application requires some persistence, and in most cases users will achieve this with a Docker volume mount (or Kubernetes hostMount), running as `root` introduces significant risk of container breakout.
I have tested the image locally without issues. However, I did not figure out (yet) how to test the trigger of emails. The only concern I have is that if the application requires `openssl` library to work, then `distroless:static` won't be sufficient, and `distroless:base` …

Low-Privileged and Distroless Docker Image

---

Taskfile.yml
backend/app/api/handlers/v1/v1_ctrl_items_attachments.go

- bug
Currently building the project inside of a devcontainer is impossible. This change fixes the problem with finding model definition by swag.
Fixes #317 
```
Generating Swagger definition by swag repaired.
```

Added parseDependency to swag

---

frontend/components/global/PageQRCode.vue
frontend/lib/api/base/base-api.ts
frontend/lib/api/base/urls.ts
frontend/pages/reports/label-generator.vue

- Fix
- When assembling a URL to connect to the API, the route function has to be called. This way, there is only one place where API host and API prefix are written in the code.
- A few typos were corrected.
- I checked that the API server was correctly responding when setting a different host name, specifically for the 3 places where I changed the URL construction (label generator, QR code and attachments).
```
API host can now be changed at a single place: frontend/lib/api/base/urls.ts
```

Fixed 3 places where API URLs were not constructed by function route

---

frontend/composables/use-auth-context.ts

Since modern browsers set cookies' `expires` to 'session' by default (clear these cookies after user close browser), remember me will not work currently.
This PR adds some logic to create cookies with an expiration time from response. Now these cookies will have correct expiration time (will not be deleted after closing browser) .
Remember Me will work correctly after this fixing.
And maybe we don't need to validate cookies' expiration times in frontend (cookies will be deleted by browser after they expire).

feat: set cookies' expires attribute and fix remember me

---

backend/internal/data/ent/group/group.go
backend/internal/data/ent/schema/group.go
frontend/lib/data/currency.ts

I have added the currencies XAG and XAU for those who wish to measure value with something of substance.
Review the ISO 4217 standard to view a full list of official currency codes including the ones I have added.
https://www.iso.org/iso-4217-currency-codes.html
https://en.wikipedia.org/wiki/ISO_4217
Example:
https://www.xe.com/currencyconverter/convert/?Amount=100&From=XAG&To=USD
API for exchange rates:
https://openexchangerates.org/
- feature
Adds two currencies to homebox.
We need this feature to serve those who wish to value their inventory with these currencies.
This fixes the lack of currencies.
Does it function as expected?
I have not tested it.
Added currencies XAG and XAU.
```release-note
```

Added currencies XAG and XAU to currency.ts

---

frontend/components/Item/CreateModal.vue
frontend/components/Label/CreateModal.vue
frontend/components/Location/CreateModal.vue

bug
"Create and Add Another" goes off screen on mobile/smaller screens:
This fixes it so that the dropdown is right aligned on mobile/smaller screens, but keeps it left aligned on bigger screens:
```release-note
Make sure the "Create and Add Another" button does not go off the screen on mobile or smaller screen sizes
```

fix: mobile "Create and Add Another" goes off screen

---

frontend/components/Form/Autocomplete2.vue

fix: make selectables clearable

---

backend/app/api/handlers/v1/v1_ctrl_qrcode.go

_(REQUIRED)_
- bug
_(REQUIRED)_
Fixes QR code generation
_(REQUIRED)_
#564 
_(REQUIRED)_
```release-note
```

fix: ensure urls isn't encoded

---

backend/app/api/handlers/v1/v1_ctrl_items.go
backend/internal/data/repo/repo_items.go
frontend/lib/api/classes/items.ts
frontend/pages/item/[id]/index.vue

_(REQUIRED)_
- bug
_(REQUIRED)_
_(REQUIRED)_
Closes #598
_(REQUIRED)_
```release-note
```

fix: images in child items

---

backend/app/api/main.go
backend/internal/sys/config/conf.go

_(REQUIRED)_
- feature
_(REQUIRED)_
Shows version info on console for CLI users
_(REQUIRED)_
Closes #631
**Example**
```sh
homebox --version
Version: nightly, commit HEAD, built at now
Homebox inventory management system
```

feat: set version flag

---

frontend/components/global/Markdown.vue

- bug
Newlines are displayed when editing markdown fields, but not when rendering the markdown content. This PR keeps the displayed text consistent between both views.
Fixes #681
```release-note
Render newlines in markdown fields
```

Render newlines in markdown fields

---

frontend/components/Item/Card.vue

- feature
To be able to see if quantity is 0 in card view!
Fixes #672 
I didn't test it!
- Show quantity in card view if quantity is zero

feat: show quantity in card view if quantity == 0 (hay-kot/homebox#672)

---

backend/app/api/handlers/v1/controller.go

Task swag is failing
```
$ go-task swag -f
task: [swag] swag fmt --dir=../
task: [swag] swag init --dir=../,../../../internal/core/services,../../../internal/data/repo --parseDependency
2024/01/15 12:50:47 Generate swagger docs....
2024/01/15 12:50:47 Generate general API Info, search dir:../
2024/01/15 12:50:47 Generate general API Info, search dir:../../../internal/core/services
2024/01/15 12:50:47 Generate general API Info, search dir:../../../internal/data/repo
2024/01/15 12:50:49 ParseComment error in file /home/quoing/src/homebox/backend/app/api/handlers/v1/controller.go :cannot find type definition: ApiSummary
task: Failed to run task "swag": exit status 1
```
Fixes error above.. seems to be caused by commit: https://github.com/hay-kot/homebox/commit/e8449b3a7363a6cfd5bc6151609e6d2d …

fix task swag

---

backend/internal/data/repo/repo_items.go

- feature
Extend the existing search functionality to be able to search by serial number or model number.
Searching by item description, manufacturer or notes was already possible by default, so it makes sense to extend the searched fields also to the serial number and model number.
```release-note
Enable search by serial number or model number
```

Enable search by serial number or model number

---

backend/app/api/logger.go

_(REQUIRED)_
- bug
_(REQUIRED)_
There are two changes here:
* Migrate to use the zerolog-shipped level parser instead of the manual logic.
* Use the correct API for setting the global log level. Note that the `log.Level(...)` creates a *child* logger with the specified level. See: https://pkg.go.dev/github.com/rs/zerolog@v1.31.0/log#Level
_(REQUIRED)_
The `--log-level` flag does not work according to the behavior stated in the documentation.
```bash
$ ./homebox --log-level info
5:06PM INF ../../../../../home/jenkins/workspace/external--homebox/backend/app/api/handlers/v1/v1_ctrl_auth.go:100 > registering auth provider name=local
5:06PM INF ../../../../../home/jenkins/workspace/external--homebox/backend/app/api/main.go:192 > Starting HTTP Server on :7745
```
```bash
$ ./homebox --log-level …
```

backend: Use zerolog level parser, set global log level correctly from configuration

---

backend/app/api/handlers/v1/v1_ctrl_items_attachments.go

_(REQUIRED)_
- bug
Use case-insensitive matching for matching against attachment file extension for automatic detection of item photos.
_(REQUIRED)_
_(REQUIRED)_
The logic assumes that extensions are lowercased. This causes attachment uploads with extension e.g. `.JPG` to not be recognized as a photo, while `.jpg` works.
With this patch, uploading a `.JPG` attachment, and the item's associated image ID was automatically assigned correctly.
Without this patch, uploading a `.JPG` attachment does not set the image ID.
_(REQUIRED)_
```release-note
NONE
```

backend: Case-insensitive attachment extension matching for item photo inference

---

backend/internal/core/currencies/currencies.json

Adding the currency of norwegian krones back into the file. There was an earlier commit where this seems to have dropped of the table.
- feature
The currency is currently missing. Danish and swedish money is in though.
- lacking currency
I've built a Dockerimage, fired up the application and were able to change the currency to "Norwegien Krone."
```release-note
Adding support for the norwegian currency NOK.
```

Add currency "norwegian krones"

---

docker-compose.yml
docs/docs/quick-start.md

- cleanup
The Docker Compose v2 version "version: x.x" key/value pair is obsolete according to Docker Compose's v2 spec:
https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements
Updated reference in both the documentation and the main docker-compose.yml file.
Fixes #901
```release-note
- Removes "version: x.x" key/value pair from Docker Compose file/docs
```

remove deprecated version specifier for Docker v2
